package main;

public class UsingExceptions {
	public int divide() {
		try {
			int num1 = 4;
			int num2 = 0;
			return num1 / num2;
		} catch (ArithmeticException e ) {
			e.printStackTrace();
			return 0;
		} finally {
			System.out.println("fish");
		}
	}
}
